version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/LogViewer.Client"
    update_schedule: "daily"
    default_reviewers:
      - "warrenbuckley"

  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "warrenbuckley"
